### ISSUE TITLE
Métodos para el manejo de organizaciones

### ISSUE THREAD

**Issue by lrromero** [datosgobar/pydatajson#139]
El objetivo es la implementación de 4 nuevos métodos, que permitan crear, borrar y leer las organizaciones de un portal de CKAN:

  - [x] `push_organization_to_ckan()`: Crea una organizacion en un portal a partir de la metadata pasada.
  - [x] `push_organizations_to_ckan()`: Crea varias organizaciones en un portal a partir de la metadata que devuelve `get_organizations_from_ckan()`. Ambos métodos deben estar pensados para que sea posible usar el resultado de uno para crear las organizaciones en otro  `push_organizations_to_ckan(get_organizations_from_ckan())`
  - [x] `remove_organization_from_ckan()`: Borra una organización de acuerdo a un `id`.
  - [x] `remove_organizations_from_ckan()`: Borra organizaciones de acuerdo a una lista de `ids`.
  - [x] `get_organizations_from_ckan()`: Devuelve la metadata de las organizaciones pertenecientes a un portal.

**Comment by abenassi** [comment]
@lrromero ahí agregué uno más para crear varias organizaciones a la vez en un ckan. En definitiva el pasaje del arbolito completo de un CKAN a otro se haría así:

```
organizations = 
get_organizations_from_ckan()
push_organizations_to_ckan(organizations)
```

`organizations` tendría una estructura de lista o diccionario serializable en un JSON, de manera que se podría guardar como backup y restaurar en el futuro o usar en el momento para pasar las organizaciones de un CKAN a otro.
