### ISSUE TITLE
Ideas para versión 1.0

### ISSUE THREAD

**Issue by lucaslavandeira** [datosgobar/pydatajson#256]
- [ ] Modelar en clases las diferentes entidades en un catálogo: Catalog, Dataset, Distribution, Field
- [ ] Quitar toda interacción con series de tiempo de la librería, mover la funcionalidad a `series-tiempo-ar`
- [ ] Partir validaciones en varios métodos individuales, separar la lógica (cálculo) de la presentación (devolución como lista o diccionario, escritura a archivo)
- [ ] `DataJson` no herede de `dict`

**Comment by abenassi** [comment]
El segundo punto fue discutido en su momento pero pydatajson debe retener
la responsabilidad de entender en los metadatos del Perfil Nacional de
Metadatos para Datos Abiertos. Series de Tiempo es parte de ese perfil, y
pydatajson debe poder validar y entender en todo lo que es metadatos según
esa especificación.

En su momento también discutimos si debería pydatajson también poder
validar CSVs de series de tiempo (datos) y esto pareció demasiado
específico, por eso se movió a series-tiempo-ar que también tiene algunas
otras funciones de series de tiempo que exceden a los metadatos.
